apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secrets/db-credentials.enc.yaml
  - ./secrets/s3-credentials.enc.yaml
  - ./secrets/smtp-credentials.enc.yaml
