apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:gGXCsjD7yPSF9uKA+v40PBbnhJM=,iv:1Ld3FeLTiqyP3+z4wB2l7rmn1MAfvmWAtEH0VjUQmVw=,tag:90o2jS4742ZSpCnfKnk0Fg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNmlGYkQzWEpadkZ0NG0y
            NW52UW5penhTc3dkcUpqSjlkVGd4ZmtGZTBFCmRxWWRZSVZSdlJYUmtrV05Xcm5G
            ajJpdEhvUzlrTkNXSUVVRjlWSVpBTkUKLS0tIGZKcXQwcmVXUEhRNHpqT0l4V0U5
            emxZM29tTFVNTVlpYS9KQ3ZHckRTNVkKF/TSohEQXuwFb9VJ3c5gpii0tD9Q3uAU
            RZRgTXCXYQJ1Yd5yprUQfd9kvN2dKm2lb48BCFicS5cYmoNFNS50nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T08:32:13Z"
    mac: ENC[AES256_GCM,data:Luupujgn02Nvsch+N9d4LLFGoHH5xmn7o6FETn+ZuKeoAplF7lU00Ug8RY0YVWI6DB+uJJBCZSJrdy3aViMLQPLMFrE07sudMr30JKtCGcJE74lheCRc14ZKhHRR+0BmqtUOrci7TuKP4yxg1fKa8i5RJu7jQRe3aR9Ad4mrJBk=,iv:pGT+Tn/jvFGUPCKc2TFVdZGqLvZ/gFxXUNhOfizp46I=,tag:WoL7G0ve5m5JnWElbljKig==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
