apiVersion: v1
kind: Secret
metadata:
    name: semaphore-admin
stringData:
    email: ENC[AES256_GCM,data:3CiqyFVjf7K1sVCTyPM63a9MjQ==,iv:0REykNPEro+a0C6kFAH/sWOgGyqQF/HfqvEtTPwAZfo=,tag:r/cyZ2I4XvJkYNYLRflVYA==,type:str]
    username: ENC[AES256_GCM,data:88ysEW0zKEy1/lE=,iv:siYyJldiFazXNYNhZ00+Flyvc+B7mA9ujj+EWUc3cfA=,tag:1WsqaxhXGlBWCsM3M4pEpg==,type:str]
    fullname: ENC[AES256_GCM,data:UmWSwGB+cm7+XVA=,iv:ApZUDIFHxrnrS+FdkXH4oS7qtRgu3HAJuRJfPIQoqTQ=,tag:0LEx36e6E0ERmPyAB1TLgQ==,type:str]
    password: ENC[AES256_GCM,data:ZPrQVpnhyxli7VTxOg2Mbiy6Hlc=,iv:8UKqexbw9cmaORu0X2dQZvHlbtTi5NqHgnT8CnaC1Bo=,tag:+BABy2RAYs3jH9zOKOJXrw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRFNRaXVoVnAxU3ZFU2pD
            S2ZGNEVENGVEMkc5bGdFZU5nZ0pRZFAxZTNNCmp4QU14ZmpDR0M1R01xN20zOFJM
            Q2t0NzltUGZyV3BpcW90YnBwZnRGa00KLS0tIHZrT1VkcWY2ZXdMYlE2TGYvamlJ
            V0xXUG9EOTI4bEU5alFsS2Ezc1VqelkK4qqIi1roU2uIjNEceGd5RUD/SvvWCZVD
            AnJgBIsdjgpsIhIRSb5xmMblpROFl7grS9Vm0q8y1f3QMV8ClLaFAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T18:41:41Z"
    mac: ENC[AES256_GCM,data:B/oAy+ZnkSQHl9VCXU6T5F0F0rvGIa59EWTwbsLwUBB58PISJ6LdYZs8yLhq3vLFLJ2lT2p+2rsuxYUWvqwBtSA1vOL0u+y7j4a1CNkwuzzPfHgxegUc6mmynf4ziHAtbo2V/FqsXwQ6dnM5btHVwqwSUXRqQDU/oyXxSGzQD9Q=,iv:jlF4veHN/VHKj+/UyRA078pIcZls8EA9f1EpLtlq2Ks=,tag:BSfwp6rUQfk04NkmiQIopA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
