# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sync-music-library
  generateName: sync-music-library-
spec:
  entrypoint: hello
  serviceAccountName: argo-workflow
  templates:
    - name: hello
      container:
        image: alpine:3.17@sha256:8fc3dacfb6d69da8d44e42390de777e48577085db99aa4e4af35f483eb08b989
        command: ["sh", "-c"]
        args: ["echo Hello, World!"]
