# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sync-music-library
  generateName: sync-music-library-
spec:
  entrypoint: sync-music-library
  serviceAccountName: argo-workflow
  templates:
    - name: sync-music-library
      container:
        image: ghcr.io/jmbannon/ytdl-sub:2025.08.22.post2@sha256:b0bb43532d07c4306653d8225f43ebe3ea11d7d672ec2d532e18fd56fabadeaa
        command: ["sh", "-c"]
        args:
          - |
            set -o pipefail
            apk add --no-cache git
            git clone https://github.com/Kentaro1043/music-library.git /tmp/music-library
            cd /tmp/music-library
            ytdl-sub sub
        volumeMounts:
          - mountPath: /music
            name: music-library
          - mountPath: /cookies.txt
            name: cookies
            subPath: cookies.txt

  volumes:
    - name: music-library
      persistentVolumeClaim:
        claimName: jellyfin-music
    - name: cookies
      secret:
        secretName: cookiefile
