# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sync-music-library
  generateName: sync-music-library-
spec:
  entrypoint: hello
  serviceAccountName: argo-workflow
  templates:
    - name: hello
      container:
        image: alpine:3.17
        command: ["sh", "-c"]
        args: ["echo Hello, World!"]
