# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/refs/heads/main/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sync-music-library
  generateName: sync-music-library-
spec:
  entrypoint: hello-world-from-templateRef
  templates:
    - name: hello-world-from-templateRef
      steps:
        - - name: call-print-message
            templateRef:
              name: workflow-template-print-message
              template: print-message
            arguments:
              parameters:
                - name: message
                  value: "hello world"
