apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-s3
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    host: ENC[AES256_GCM,data:WrWX3pL3k28OkyXthQa3qopO0xxDGu2TOo6Q,iv:ARXARko6oqcPHrgYOFWXlUq3JB0nFrOxQxru0P1bg7k=,tag:fbkUYUDwKaw4HSKee6Yx0A==,type:str]
    access-key: ENC[AES256_GCM,data:kc3OFcRnkHua,iv:ywrJRK1N0qvXaA2noZPOwwhdEQSMYNTHl0/TNSCkKHI=,tag:u/w7mhIA6jxAb05wERnYGQ==,type:str]
    secret-key: ENC[AES256_GCM,data:NiX/kDYzQ6WvfIcUp7S9WDLpYdw=,iv:1Rv+MkNT15Glwi+LBA4UKlbwSMbHZlsILs+q9oTjuCw=,tag:gQA4wvJ+Hlcogqx/tBA61g==,type:str]
    bucket: ENC[AES256_GCM,data:mvTri9amg3XA,iv:CXq10wVKicCW+In0MI0DyjuuExLLWXzZdMDkRnt94pY=,tag:RCmpCS/7Q8V4IjB389xqTg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ3hnUERJWWdiZlV0VXcx
            ZEpRbmlzS2lHYkdPTkNWNXFOS0ptUVpVQWdvClNXOWttQlFWUXdYTUZTbE5PbWhR
            RUlsbUZDY2hxd1J1aTZ0Y2NJamQzVUEKLS0tIG9pQUNWeDMzRzRCVUV1S2VhaCt5
            MWxnbEQ5amczN29qSVlFU0ZDamFGeDQKuj+PmtV1/dz1SQCw4FFgQLOIj+0T2Sl4
            Ac8isWbGEvUks7onvJqfbySxbPwOF1VRmxvUfX1wayPDxPYAvGjjwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T15:53:56Z"
    mac: ENC[AES256_GCM,data:KLY4PQM0sik/i4iFesEwKdAlToTcp7mVls5P2EX+peGTcZGLw+JCEfX8dAb1AivFD1X9kRf9wDy+QytD6mkSSVob32xg6ZPAW7Tj50S6OpMNbl+h5Lid8VfYAZTFnu7+W34XhL5M5srigFGozO9McSxq0SkU5ZKGNOmlWhD3po8=,iv:dwna4ZodofJr5AckJiPB6WwAn4Of8G0QdIFpLcpJ394=,tag:xkr5J66XbJh8f6kZuygc9w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
