apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    username: ENC[AES256_GCM,data:bS2X8gAcqNcCFd+4GA==,iv:mBjuZibM3LDH5s2flrkvkTvTybHz+T7YgqJ9Kjo3FRc=,tag:GE6GxQ7BmW3E+lm66xOPEw==,type:str]
    password: ENC[AES256_GCM,data:i1Ty3fjMoTW6rf6c4vCeomWfkUY=,iv:NapHzV+10Ie4Jrz2qasLJvYFcONlaAYGtbDOSGJi+rw=,tag:+CBDnycqMLQJGhCbIqAzXQ==,type:str]
    smtp-username: ENC[AES256_GCM,data:71KMFiWix8bC,iv:gVofD8s2BOhEoCd7D04osVVBVVUTtSalflcnpGiImWc=,tag:PmekzY/NctjksMLcrqr3Ug==,type:str]
    smtp-password: ENC[AES256_GCM,data:1kwDsW6gvuVeK883LeTKrQ==,iv:asOvdAv0inRhfEnqD/oyZoZdjYj/V4lROKtT+9GabSM=,tag:s+qxMzxdIvrScGsXNcMJFQ==,type:str]
    smtp-host: ENC[AES256_GCM,data:MI4T+Nj0DB5EfU0Urxs=,iv:ZPesbxSA9cx7job/ia1ivnbomNqmmHyA4wZ6lGBTPwI=,tag:Ivuq62Rwxo6W2wJnCYHghw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTQ1LzlLVGcwK2JPOHJr
            Y0pPeGhpVTVsY2N1ZmZoWXRNdUVDcHZmV0hzCkhJK3RFUWxIb1V5WTIzR1Q0Z2pP
            d0VSeFlqMGYrcmM3NHR3M1hlbE55eWsKLS0tIGhkT1RiQi9KaTNBVEJEaGNZd1pW
            SjJ4WUhyM05TcFVZdzQvTURvNFFFVDgKkIn7dX0lxS8KmAEiaqA8LxvLvdQ4kfSV
            P5HX4Zcr4iFagKG36LSP9jX0WTFqNkeTaKQ0oj7vproczEiBivkigg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T15:54:03Z"
    mac: ENC[AES256_GCM,data:1/XjsAEkW4VVXPGMafsXxhrlw+advymnTxjUQiTBYyJlM1Y9yDsQ1aFrw4EsOov/VW6SdfAUU1a0nlzpdWciY2ulYsR2sAUAa8wfenwSw5BMNN03hUv7eeMZV0wPWLEStBAkZg3V7ctYgGQ/46B1DoG0fkdkdUatFQy2sLI3duE=,iv:zqZ3QM4h+KQo6AtQgX1AfPG0B2cYc2CFLZyf3iN4/1E=,tag:CsMHxFqtBkpqA6gmssvzhg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
