apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    username: ENC[AES256_GCM,data:bS2X8gAcqNcCFd+4GA==,iv:mBjuZibM3LDH5s2flrkvkTvTybHz+T7YgqJ9Kjo3FRc=,tag:GE6GxQ7BmW3E+lm66xOPEw==,type:str]
    password: ENC[AES256_GCM,data:i1Ty3fjMoTW6rf6c4vCeomWfkUY=,iv:NapHzV+10Ie4Jrz2qasLJvYFcONlaAYGtbDOSGJi+rw=,tag:+CBDnycqMLQJGhCbIqAzXQ==,type:str]
    smtp-username: ENC[AES256_GCM,data:71KMFiWix8bC,iv:gVofD8s2BOhEoCd7D04osVVBVVUTtSalflcnpGiImWc=,tag:PmekzY/NctjksMLcrqr3Ug==,type:str]
    smtp-password: ENC[AES256_GCM,data:1kwDsW6gvuVeK883LeTKrQ==,iv:asOvdAv0inRhfEnqD/oyZoZdjYj/V4lROKtT+9GabSM=,tag:s+qxMzxdIvrScGsXNcMJFQ==,type:str]
    smtp-host: ENC[AES256_GCM,data:MI4T+Nj0DB5EfU0Urxs=,iv:ZPesbxSA9cx7job/ia1ivnbomNqmmHyA4wZ6lGBTPwI=,tag:Ivuq62Rwxo6W2wJnCYHghw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d0VvbkxQKzJFQWNVOVMr
            eUdzTXVXYkNZTktZUmZsa2xpc3N5ejlqR1FVCjhjcUx5MkpIZ25lSUtxbGNuR1Np
            L24vK2gya0E5OFFDVnJIVGlGWHphbEkKLS0tIHI1ZFRpc2lsaTJyMUREbnZubWta
            WEpUbjdTQ0hBWGZGSFlKcGh1WDdqSGMKPJnFWsd3IPWuefPuSUbfXftMppyTBNNP
            pryl8aWcEBn1I2tepM70tLdNNd/MT2ZSf/jtqz3g2w7eykPNa1BvJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T15:54:03Z"
    mac: ENC[AES256_GCM,data:1/XjsAEkW4VVXPGMafsXxhrlw+advymnTxjUQiTBYyJlM1Y9yDsQ1aFrw4EsOov/VW6SdfAUU1a0nlzpdWciY2ulYsR2sAUAa8wfenwSw5BMNN03hUv7eeMZV0wPWLEStBAkZg3V7ctYgGQ/46B1DoG0fkdkdUatFQy2sLI3duE=,iv:zqZ3QM4h+KQo6AtQgX1AfPG0B2cYc2CFLZyf3iN4/1E=,tag:CsMHxFqtBkpqA6gmssvzhg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
