apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-web
  namespace: misskey
  labels:
    app: misskey-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: misskey-web
  template:
    metadata:
      labels:
        app: misskey-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: misskey-web
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: misskey-web
          image: misskey/misskey:2025.6.0@sha256:217a1ad34bdf26227ba40ea19e0daecc52194d68cb11ce18e790c1c6e3699d51
          volumeMounts:
            - name: misskey-default-config-file
              mountPath: /misskey/.config
              readOnly: true
          ports:
            - containerPort: 3000
      volumes:
        - name: misskey-default-config-file
          secret:
            secretName: misskey-default-config
