apiVersion: v1
kind: Service
metadata:
  name: misskey-web-service
  namespace: misskey
spec:
  selector:
    app: misskey-web
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
