apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
spec:
  secretName: n8n-tls
  dnsNames:
    - "n8n.kentaro1043.com"
  issuerRef:
    name: http-01-issuer
    kind: ClusterIssuer
