apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - hard
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: private.oci.kentaro1043.com#srv/nfs#n8n##
    readOnly: false
    volumeAttributes:
      server: private.oci.kentaro1043.com
      share: srv/nfs
      subdir: n8n
