apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
spec:
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: n8n
  accessModes:
    - ReadWriteOnce
