apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  serviceName: n8n
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:2.9.1
          ports:
            - containerPort: 5678
          env:
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_HOST
              value: n8n.kentaro1043.com
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: NODE_ENV
              value: production
            - name: WEBHOOK_URL
              value: https://n8n.kentaro1043.com/
            - name: GENERIC_TIMEZONE
              value: Asia/Tokyo
            - name: TZ
              value: Asia/Tokyo

            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_HOST
              value: private.oci.kentaro1043.com
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_USER
              value: n8n

            - name: N8N_EXTERNAL_STORAGE_S3_HOST
              value: https://77cda51d81436ca0fab12e116c6d2a4a.r2.cloudflarestorage.com
            - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME
              value: n8n
            - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION
              value: us-east-1
            - name: N8N_EXTERNAL_STORAGE_S3_AUTH_AUTO_DETECT
              value: "false"

            - name: N8N_EMAIL_MODE
              value: smtp
            - name: N8N_SMTP_HOST
              value: smtp.resend.com
            - name: N8N_SMTP_PORT
              value: "587"
            - name: N8N_SMTP_SENDER
              value: service@kentaro1043.com
            - name: N8N_SMTP_SSL
              value: "false"
            - name: N8N_SMTP_STARTTLS
              value: "true"

            - name: NODE_FUNCTION_ALLOW_BUILTIN
              value: "*"

          envFrom:
            - secretRef:
                name: s3-credentials
            - secretRef:
                name: db-password
            - secretRef:
                name: smtp-credentials

          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n

          resources:
            requests:
              memory: "320Mi"
              cpu: "20m"
            limits:
              memory: "640Mi"
              cpu: "150m"

      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
