apiVersion: v1
kind: Secret
metadata:
  name: headscale-client-secret
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
stringData:
  client-secret: ENC[AES256_GCM,data:aYLpFsfRqdwkt12r/WdQB+G7AKEDRZjYXyedOBTwj+aMgdJO,iv:SFRuQf7eoSNfat9eD5WCI9EpQq0mJYsK2QU1IUICsbA=,tag:RTNKpEuUVXUwuyM4aIUvSQ==,type:str]
sops:
  age:
    - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RHd3ZStvSHk3SnB5Y0V4
        emM3NnFySzFVYzJsQ0FubnhjRDc3MDM5MTBRCjdFTEdEWnMraHlmS3g0TlB2cmJk
        aUxJNmdCOTk1dW1VUExJRGVHNmNpT1kKLS0tIE5JRWVCU2duMjdtSGJjMDBQcUNQ
        czFKejdCUGduTlY3NkEyZ09TaS9nMncKSj1+E+HfpRDamqfoiJTKn4Pu/Pvdhjye
        rd5IaULPIoggbuSk+cI/IQLF++vpCOs9u2dlZ5aLoabb/oG/q6NFUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T08:41:01Z"
  mac: ENC[AES256_GCM,data:AfxKwQYW39sBFHQbSGe27ePyZUCc+ijXbm/yXOoOCb3+oSzkEOivyGfQ8Yo78KW3Bdy7LPTwlcRvStt5IIy+7NmD7YU0YMCktnXE9m4NM1xpbLs9TxQ+Tgen8L3e80D0OLNtVUyT9NRPPQ8+yB8FYptyhFtFmBm3LlYM+UO7/cY=,iv:tAqGNwCqyt8moYc13P1XEdI+uTZWyuHAWxUNkGEUBAg=,tag:VHUDO062rLe6Td3uVNhIew==,type:str]
  unencrypted_regex: ^(apiVersion|metadata|kind|type)$
  version: 3.11.0
