apiVersion: v1
kind: Secret
metadata:
    name: headscale-client-secret
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    client-secret: ENC[AES256_GCM,data:valmrLlznwo8yBLr/RpSlROzuQrqMF2PqWQjEzCF0e6lcAqQ,iv:H7ul7jKA9bG18k4aMUviED1Ut5lUXj7IsCAfv4HYyzY=,tag:pW1HOUTL4cHH1bL1XSZMSg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNGJEVS9weW9YVDZaMHFJ
            TzlPWlU5dWREc05scDd4N294YWtLSVoyNEJZCnZ2YkxlUVhsWEtOUHBxZGQ4em5v
            dDZUTWQrRWlVT1VScmhuVDVHdnFkT28KLS0tIFQ5ODZWUWY4WjRmcVVIbWRDS0hw
            clNMMjA0MSswVFRDZkJJZkoyV1hWbjgKosb5kM7UGX50o2+CWras4OlNP3tDv6pI
            pBTasraugJ8FqOwx9M95lcMPb+jnriIgizOuimMV93HWbkZijGVKDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T00:09:24Z"
    mac: ENC[AES256_GCM,data:Ec7aePAoZJW1GK8Zi6/nnvqO0FKsLJX9Zcq1gnGAvkTCmjo5xDUdrdrAOhMWJbDHcVLrv+FX7JDVi3wQDxclDepQS9ovnh6+fIScrI2iGAjN693Fb8g3naJAOSVyYcN+OVLw5YwFRCG7FR1HnjvF5Vgc8h3ePfjrp4ooUUAkMbo=,iv:Ws0dlBLXWvUW0L+Evj5XR0QVgyKb2Z1AfiDmJiz52bs=,tag:6Os1f8PlNWGriCFVkDaSkg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
