apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
spec:
  secretName: vaultwarden-tls
  dnsNames:
    - "vw.kentaro1043.com"
  issuerRef:
#    name: http-01-issuer-staging
    name: http-01-issuer
    kind: ClusterIssuer
