apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secrets/db-url.enc.yaml
  - ./secrets/push-credentials.enc.yaml
  - ./secrets/smtp.enc.yaml
