apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-icon-cache
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOncePod
