apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
stringData:
    api-token: ENC[AES256_GCM,data:PESimM/Bu4BzHG/2L8UQ1okmGhhYgN/ZgQXejvbeYdHE+Y29r761gg==,iv:zS9ny//dZAUaU+FkQFBoTF04EDHA/IU/6QiTAO6QoUI=,tag:KgZCRr1A9+bIORvzCu83+Q==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQzFoNWl3c2tDNm1EdTh6
            aUQvdkhRMTBIcStRcC95cVBmNEFQT2R5QjFRCnN3YnlUWjBMTldxWWVtVXJQWGpw
            SWJTY09IdExuaEdWOEtxWG81bFhITDgKLS0tICthQmU0RDV3UTVIN0czSTVzMkJH
            Uy9wRm55U2VhS2ZINU1DenNZdFBMUkEKgz0VVOSUadZ3x4Ifq8e/SErwHYbcsoVr
            jzWYPWii89c8/ioxRBpOR9WWKP8HUKXMtCtPFD7MLkjzPI7DhJz61g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T13:24:09Z"
    mac: ENC[AES256_GCM,data:1kdgOY49sJXP7rytr4UevJ2sG18nhp62Bz2vbgeUc99F2tx1lMdZponhQQCqzk+achkJbKk2mboXVolrsxBu52AImr5u3AFakrz6C5KXAfQn4RSv3aRLYY0RK5coj7t4DLmsK5mwdJ0/mnKb/cKGIsjroXBylTABPMKHPx1XPH8=,iv:9j0HiT8HgOjCeacWnkw/cCL6su2gsf2jZQBMG4I53tY=,tag:GLzRTXSOlZyGboKwzoL/UA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
