apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-attachments
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOncePod
