apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:9f2b77Teu9AoPPSDX2YefGbVVc4=,iv:CyktzTD4haMA1LichbS9nt9zBYBrbdvMiBlhi+nb/yU=,tag:CVo6h6VNITTac4R7H3V7ww==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:D8FfUNMDzRIN7SeSwu/aWZ0NE6U=,iv:j5/Dgog6wUWjRp59Q3h2x9w28QJXh0sxkT6Flgd0yXs=,tag:TQGMN5Gx1+sivgdH+VvA7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaXZsYzg5TFFCRktZVWlw
            VFFPRWt3UTJkKzdlOFVCbUFUa2hjc0lXTWkwCjhlbXdpWTB1STBEbzFmK0lXWjAv
            ak5jem1DcHlRZ1g5V3ExbWtraFBrVk0KLS0tIFhxZlM0L1c5WnZVTjFRbEFqZVI3
            M1Y0WXpFcHVBbVpKazFaOEZRR29jWTQK+7/D3G9qVpnnaswzsvZeKVTukeTtUGYw
            IrjZDOk+Q7/4exyn4FaUePsKg0hxzbGGuMmsj3mQ6H26EGohCv+d0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T07:42:09Z"
    mac: ENC[AES256_GCM,data:umGF+Gx3AVZql+aS8ABAYvajSzU8zd/Khey/1Ex4zYDOuX2C82krhW0TcfUQHVCnadVDvmXiERq1/VLMfHcUGU6nY/Tpb9DU8n/VSSaytkwiIiomjs8ALM9adMl9iYHocqv5K1x9Sz5yGa74/f1Z2vCBPfUCs5U93WJASh1PzGE=,iv:ZMQgwk3BT2ADxfkcryq0ueXzK4g0C/4DzR8vHYXV9NM=,tag:3djqk+NPwAcnlDXcVElkQA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
