apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:oyLu4EaX8VWN+Ls8kcFSfZ2Z+4s=,iv:1AkYeOJ3RWQxi6zIkdXzjW7XcaX+m4f4vnY8NP1/GJc=,tag:w2x97JUzENndu5thIVYQcA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:kxUOj62ph1rPU2FTzUqLriKZPC4=,iv:g1NQyQHU7WvD3UZgRKzMc6p4JM8Acvz6FgQ0Lnx9II4=,tag:shnTqoz3wp39FsxApb2TSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWkxoQjNvdTJjMVlRRXNj
            dmttL1pSanQzWWsrWFg0bXZta3V3ZVpxSlJvCnJ0NkI5UXhoT0xLdnRBNjBFcmNU
            MWRTdjZmT3V3NUludElyekpPUEoyZDgKLS0tIGl2bjJzaWtwZmcwQTVUdTdQNmVV
            UUdmK05FN1pja2gxTzJRbUdKZlIxUTgKp5XYFJ5gtWkmKHIirZCDRyQApDHxD2k6
            O6cBiN754ssjNOb9A+90i4RSkP9AspuBmN39MppDz6bhTzJuNZMTkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T06:20:33Z"
    mac: ENC[AES256_GCM,data:NpsMWEgQfRrDMILzcVjHCou7kzfZ0g9+zUknsiL9CYmmgcu/9sd1mZ0eO3IW0qT/feVmbFSO3PmV7Lqi1+Lj7h61UTePTvCxgzkoo4XduDUzYkdpO+5im0HtfM+0/pGmQT4+m6WVvIQNuKPaGaF0DBS9hDSt+o9RioiE3gjV8rY=,iv:CUj7kNWzZtAOTqLKxMIwcxa3fl4eW72zUkNIT5SbUpw=,tag:NdG0OOtkKal4I5rxs/FDeg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
