deployment:
  replicas: 3

ingressRoute:
  dashboard:
    enabled: true
    matchRules: Host('traefik.kentaro1043.com')
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls
      certResolver: http-01-issuer-staging

service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
