deployment:
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.kentaro1043.com`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls
  healthcheck:
    enabled: true
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
