deployment:
  replicas: 3

ingressRoute:
  dashboard:
    enabled: true
    matchRules: Host('traefik.kentaro1043.com')
    entryPoints:
      - websecure

service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
