deployment:
  replicas: 3

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host('traefik.kentaro1043.com')
    entryPoints:
      - websecure
    tls:
      secretName: traefik-tls

service:
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
