helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm
    version: 7.0.2
    releaseName: nextcloud
    namespace: nextcloud
    additionalValuesFiles:
      - ./additional-values.yaml

resources:
  - ./ingress-route.yaml
  - ./middleware.yaml
  - ./certificate.yaml
  - ./pv.yaml
  - ./pvc.yaml

generators:
  - ./ksops.yaml
