apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: nextcloud
  accessModes:
    - ReadWriteMany
