apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.kentaro1043.com`)
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: authentik-tls
