apiVersion: v1
kind: Secret
metadata:
    name: push-credentials
    namespace: vaultwarden
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    installation-id: ENC[AES256_GCM,data:P6nvHekehLy3/7ycbSblBq0AjuSPccrQCH8zvUGzhFiSh3kC,iv:GvrLZbB41q6o/0QmRYUaz6cONEPEMlr1nFbJA/X3cqA=,tag:CtLzhwnrrxG1xaqWnWZaew==,type:str]
    installation-key: ENC[AES256_GCM,data:EgrB+k0BrqOKCv93aYGFrqgOXN8=,iv:gODEerlZnM9z1swhFjJPEGmQumgcgrXrs2m7iN2d0xU=,tag:jQTY/kirIysVtH6kcTeHDA==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITTROYVJRUTh4UVNHT2o3
            TkZuVUtxUjdsT2k2T2ZXUHBxQTVJY0F3cmw0CjExSUw3L2o1MnNld1dZYWZnZy9o
            V3dFdjFWdkxSQXdPenBIOEQ4MDUzTGMKLS0tIG8wLzl5TmovU0g1Z3c4UGsxVnU2
            QlR0TFNMMzhjaTYwcll2V1FzcFJvQjgKpFMvOfGBmInRBst9MZRK4GVHfjdeepW+
            rWCw7yUNrqraizrl22eQikN5yrsbJJZHlqVi27j13zXIcHIGoX0IRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T13:20:38Z"
    mac: ENC[AES256_GCM,data:AYvZdk5VeUzG9D1hEpUXwemjSIQbaGITf/Jh09yc+arPQtYHZIAGSGRZsazHWS+4NfvjDCze82QRBPxxQv7vBLncmUDMzVhl8tsvv+6bn65X/cPAiOn01fJ6TXW/e9AjR3nllkT8fuI5uAFgOsj3fG1eciSHswUOcoZxiNoVGOA=,iv:In0Y1Laph1g8XrO8+rftJUXEQRBeq5HzuI3pG02naoQ=,tag:i6hPy+MBzwn4FRR6nL5euw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
