apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-push-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:SR56M9aOzl+FAN3gDYltZEmIJ4foL5IjdQ/cYZ+Ksmn32tCd,iv:zrByOEjLgNtoySm8hHH8qQdUYPRzwzsmf+PB4WHbBUo=,tag:enSCzmA0bij4GwJUdv0Fxw==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:xJt+u+8KTJgoFPNC82Xbk2hMPYk=,iv:8S9F/pavmbnlsBUfSX5PBAJ4Ob17Tir8I2gLSpDnt0s=,tag:fAE82wwz9n6pzONbYGFQCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQS9EK1VGV0YzVFpEL1JM
            SkFqaDQ2anNWWDNxNUk0dnA4YURISnU3RkhRClhwaGpZRm02czJOQWoxN1dKNGRR
            VXhCSjRqQXQ4TkZ1Q1RBNk1vb0xNTk0KLS0tIFVOdjI2cSs0RWF5ZktrNHlDcmps
            TFBvRTJnNzJkdldsUHRrV3UxOTlvVjAKCGDfADrfkQ/C5n0MetsbMcESTlJR38Yd
            zAk6+p76/227jSJV3chZBDA8j6/Q07jwtgqqSy9j0gJhLqhQz/mSpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T17:27:53Z"
    mac: ENC[AES256_GCM,data:+ihCVLJm0WW4lfembBOLdnxhBf8lgSMayJyk/pQkppzyWRYm8KH4o7tBdGt6sGP4tjahzOJ5Ro69KrgVg+Gg4XLj8XestLzoqHsjs00qF1O8swR0T4Eeh8Cv9owXJ2EbtTz/ZHaD1WXWOA9y1E9vEuw1x/AjA2jW7zZJDbux5wM=,iv:bqPzL6GM5HCkMwMHDdpC5hHmdabGT32kxheM5Izj+Yg=,tag:VLmO5pNU+KWwb43TJYvEXQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
