apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-push-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:xABVWOiVrLcfIS3EQXrkr9DdJIWha+I4069TWihDv96lDvT8,iv:EYbSkW9Tx+fHxxXyI5u/vfCchCNrY6NiVf9Yr/nrITE=,tag:wFRNna2h3eLFhgkpBnOxNw==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:VMRhEq69TO0Og7j8pBsFoNdwE+s=,iv:aYImsx8F6sflPgzg77K55woINpfqQNYF24C5aD4nXPU=,tag:UDp1RCuBJLIK5bCDSlLCfw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUG5QUlJTREFXdERScllF
            SjVpek9MUzFsOXdNYVNHTVpWd290MjJIK3lNCm85SlpjbzI4L0lublVVVklXY3E4
            cXV3S29XcmVCdHB5OUpWT1AxRWgxSHcKLS0tIDlkNExoRG9CR1hFRmVlVTMvL3RE
            Y2pXUDhCbFJkQ0lGL3pDNlM1SVRsYjgKIXJHdNLrX17bq8cUypdRRMl/ptDBdRwY
            WxP8xiGHez+DoUWHFdo/53Z70SqHsHMZrVXt/SU4MK1E6fpaF4CSNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T13:07:48Z"
    mac: ENC[AES256_GCM,data:i4IQ6iNGYtr/EGn2f8P+MMqBPByWvX52z0hjDc7SKYzsJ5YK2wMXvdp0ISkPGh0D4+7TnxvPfkfnajLsIadZwwps2RcmXM5+mddU6SzBOT+0KXmdQ1MnoI/0QpG3P1RqRj2ASg96vS3JBGK9TcMqakRGqgoHneB0hn/CR18+v1g=,iv:+RGD5kmZTijFKR7n+rqbvqoOqmEQ8e7jbTxa80O4EJk=,tag:tXjZPph34x/b0iZHVBlJog==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
