apiVersion: v1
kind: Secret
metadata:
    name: smtp-credentials
    namespace: vaultwarden
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zUNA/uaz6Y0CicnBlKcLwE5RBQ==,iv:AZL4Jn01Vuqv8fXYJcoYsrrdM3o4Teo115Rm2kE5qOI=,tag:UiaWPqqwTTQF5no6uznMIw==,type:str]
    password: ENC[AES256_GCM,data:4+uGzbgoqUNxkZs2wXiZ1A==,iv:e5jUOosHfY4x4GfBijocvaDyfwjZ6fR0st8M+Zf9hro=,tag:ieOVVLD7BjyQXlrs2+r4Rg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobVFqOFZUK05idHh2VE11
            RUI4VkU4RGdVODlpeWd0ajROY1hFKzJmRXo4CmIvNXdQRGN6ZGJ4UEFFZ3RyR3c1
            SHZWaHl4SVREdDlnaGlWclpNRXNxQXMKLS0tIG56RW5udTBXZk1UWFNadUtURlht
            Yk5CVCtRRDZNUVFvaitDK3hTWEVRS2MKvgU+XIiHbaDLCKFJ4ai3bC1e6RkQYh0e
            0SgY3L9y5FH48+jahWSZRokMtMCxU3srLix7AREChYiHB6bAO95vvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T13:20:43Z"
    mac: ENC[AES256_GCM,data:zYstjEKQVjy28U6wYOnzes96jM3UuJo4pUZCF4UwQJ5qDtknMe8Qp0XSwr16n10h7S/lZygHbkOkdVqmADSApIhujF3spV8SQoxtRGaKxzaSNhlB4gB3D1lPOOkqT1SwFF+lxTLpa3sCGy3EEQyNnZ07P26oIX4rYfqGE2xvWwY=,iv:5eYeVyAjGIjtnrEaD46T1SsE6KT7xn4jb3NqNTlI170=,tag:Q3FVqX6CZY/dXOWE/fMR3Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
