apiVersion: v1
kind: Secret
metadata:
    name: smtp-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:93J6CXryqZUNJjXscJVEiOSFGQ==,iv:E5c2rEY/29cD2VyIT0VNCDiPrdNTmiBv/I/oDRA4sqY=,tag:hsoOIDS2rfKvT3mCLMfvpg==,type:str]
    password: ENC[AES256_GCM,data:E0aMnSiuChcRVVjHHgBdVw==,iv:QZuKC032tdwXl6kUNkDg+oQ1V/aGvMWNTFTCq0O+hvQ=,tag:j9SW0hDfuejPjR+mPip4bw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QmJEOEdnKzZBa0ZuUGNE
            bHdrL2NqallqZEkyWDIwdUVJSC9wdlhlZVhjCmZtVk45ZlJqQmRiV3ByZmdtekt5
            SHN2Mmp0QmpNNFFpNWZvMHU1QlB0WTAKLS0tIEltY2hMYUc4Qkx6OHgwb293R3Va
            Yk5zMXRWK0VjMTMzcEVSRWFWY0xxU0EKzNnAVUr+5uF2QSExgubme706rFk87Vvm
            GMaxJ1dHYLYqwTRTtb+Te1Rckdvs59+g2plhhpb+EiLKVy93GOZbbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T13:07:46Z"
    mac: ENC[AES256_GCM,data:MhTmcm3oJZZCDI6hNq8ufLDN/ze9D27hdLR2mudPFPJsvSUpHSTcU7281HkY+Jbk3OhifiI+tc1Hkfaga/jGgOJJkKZk5b6QgBRB22sJWzR2GZRCdLPrTrjSUGE7yVzaQRddlTcFzZ9TOcSBPC2usyge7f44q+rnFvjvr/LUvic=,iv:9wSs6NkX8MKsS3g1h6Pd0WpRedXkXAnK8JfADc3ozMY=,tag:sJts6jh4Dtfpper+hs3RYw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
