apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cgps
  generateName: cgps-

spec:
  schedule: "0 3 * * *"
  timezone: Asia/Tokyo
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: cgps
    serviceAccountName: argo-workflow
    templates:
      - name: cgps
        container:
          image: ghcr.io/mrrfv/cloudflare-gateway-pihole-scripts:main@sha256:769e62ed5986602c6bb78225e5778344dfcf181ebac49757bf08ceff6c5298c5
          command: ["sh", "-c"]
          args:
            - |
              #!/bin/sh
              set -eux

              npm start
          env:
            - name: ALLOWLIST_URLS
              value: |
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/banks.txt
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/mac.txt
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/windows.txt
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/firefox.txt
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/android.txt
                https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt
                https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/issues.txt
            - name: BLOCKLIST_URLS
              value: |
                https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
          envFrom:
            - secretRef:
                name: cgps-credentials
            - secretRef:
                name: cgps-discord-webhook
