apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cgps
  generateName: cgps-

spec:
  schedule: "0 3 * * *"
  timezone: Asia/Tokyo
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: cgps
    serviceAccountName: argo-workflow
    templates:
      - name: cgps
        container:
          image: ghcr.io/mrrfv/cloudflare-gateway-pihole-scripts:main@sha256:dbcfe9f6f33bce8981276d4b21a7d1af8b00e4fb2fb912ceacfda8b71dda5917
          command: ["sh", "-c"]
          args:
            - |
              #!/bin/sh
              set -eux

              npm start
          env:
            - name: ALLOWLIST_URLS
              value: ""
            - name: BLOCKLIST_URLS
              value: |
                https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
          envFrom:
            - secretRef:
                name: cgps-credentials
            - secretRef:
                name: cgps-discord-webhook
