apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls
spec:
  secretName: portainer-tls
  dnsNames:
    - "portainer.kentaro1043.com"
  issuerRef:
#    name: http-01-issuer-staging
    name: http-01-issuer
    kind: ClusterIssuer
