apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`portainer.kentaro1043.com`)
      services:
        - name: portainer
          port: 9000

  tls:
    secretName: portainer-tls
