apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  namespace: invidious
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secrets/companion-secret.enc.yaml
