apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secrets/webhook-url.enc.yaml
  - ./secrets/traq-oidc-secret.enc.yaml
