apiVersion: v1
kind: Secret
metadata:
    name: db-password
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:tSJi6JmAyTU+mut0WGLB4WQ6pC8=,iv:FjOtgo46ARCRLAiiOdp/kUBGeVzDnUvexVNfn+joPcU=,tag:fQd8srzRWMrcQTDU3M4lbQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcUU3RDFjRDZXNGV6eWRs
            UVdVbm1Jb1o5eVRuY2dOVlp0NHdUR1JueURBCmpvUkU3RWp2RVpzSXc4YTdyL2Fm
            MzR3L2JYQjRpRUd5cFIzWXB6ZThvQlEKLS0tIEZmWW16dzRwSUFyLzFtRU1FODBv
            ZFA5MVF2VmNGNHd1aWtxaURyUmZDK1UKwz0ljh7VFgR9NOecsIeERSeOb4xoxSQN
            BI8Eb5WN61I64jbmhgaUuM+tsDed2rt1NRZByU71CXPpzgAUIAng1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T09:11:19Z"
    mac: ENC[AES256_GCM,data:GaUxmYaDs3JLzalXpM2nO/J2tLktk8gKfjPNSt2vs+0AXb9n+pAYtp4E0JF+0RdIUimY2Aqvzxu/zzO5afOpZw67+50tpE4fJZofJCsfkHcGBQBk8dAociQgGT73fWoH1yTPFUXBV6GaLOJffzrV2iyBxwhbAOZndfAiVuoxs/M=,iv:R8zSEnJdTz2AcZ7myToVIr5HNGBMlu1AbqEirvWXrDo=,tag:ekQabK29mrFzpQPbWcbeeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
