apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:ZKGLI6aSslRjL5Qbw9PwVmAKpwjgclhj89wIMzfC5lM=,iv:7hQrOO3IXVmfT1hrWMgBN6+gXmXSVHGz4/66GkMzzF8=,tag:WAQPOQT9lbBoUDfjC5gX5A==,type:str]
    N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET: ENC[AES256_GCM,data:/lTg3wynD4nR7a4x+0sO9z4T5sh3YPSGshcv+gzW0RtNYI0NDMIQMKmBqxysUCGjkVmHaKLVpJu3gUacfuBaDA==,iv:PUO9Dp3XYqE1OgbtlXbJltM42GJe7htcOV2gB1PLQK0=,tag:tQhn3haMhGtX5c+zHae7eA==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeDc2VzArcWVXOFJMcHQ3
            VUJkaFI0d2NVaXVFUzE2bk1iakgySmd1YkNvCkhrckRScHNyVGJqcTZ5UVFaMXEv
            VHR4SzVsbHBKN0YxV0Q5djUvaFk5dmsKLS0tIHBpWkV1TjVnYmdOZG1iYmVOOXly
            cWs1bjltVHpIOWJzb21mVmVvdVRGcVkKctkHEBU6hKwGz99/sRwX0L10Q3Szbzd2
            6xFtHBRQr/FSDWpdot7RcGYxBZ0YDF1miw+4WLXThVjx4dI23OriJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-20T09:12:42Z"
    mac: ENC[AES256_GCM,data:Zy7IcVx676cGbK3ioK9+FjUeKt3jZNFwhXPpyc1tovup09tcHuyqYwQZKi4xcdWh69bNC5Pa2DcD4uh3gzX8mu+pzCg3vGaMoY6efV8Uoilzed7yxOvo5Bl6+B4jiNLUxF9Ir3X6Q6h9CZrzx5ee6upTfofFDAJmNs0Za8qPtEU=,iv:kSn8uRNns7qYfkxWJEGk+F5BMpuX9/I1qciXjk/T1eI=,tag:N28fjGO5gSTqrHsPF3/ebw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
