apiVersion: v1
kind: Secret
metadata:
    name: github-webhook
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:82SbqtRMpu2Qt44DNsYZs3D61QjiLXTECQbkaQZKf4at0GK9TPSUtw==,iv:jfwsQWqBIY+lx4hptofoechgZJ43uNd0cjGewogNvYY=,tag:+ixZ4vOWeuZi+Pnlk83f6g==,type:str]
    webhook-secret: ENC[AES256_GCM,data:E8Jvf788jG8BTkcvQP1r8g96AqD9DdgE3psZ1G7+68E=,iv:UwikyCMLHTrr4eSylLX62aWllYjONUKszteOQXgL4Po=,tag:xG4EEOJxr21yeP+oAe9oDQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS3ZxVEN3eDNnK0FMTkxX
            S0ZWODRGRGpwOEwva3gzZ3I4YmtnNk9lMjJVCnNEN253dVVmTnVPTzZLY3hocktL
            ZEVIWk5XY2k5Y243SExjQlA5bFU4MFUKLS0tIGZaK25Hb05SVDB1SXdvZ3dZMHBw
            eWg2Nm5EWkRuVzMxNExyQWE3UzduNHMKcwIXoA1Q95YfuG7/qFzhIaTvzzxhDouB
            i/vOB/cMvCIbR9Y4b39U1NtNFEEVImZj32GqEE4+4UjL4k/YTmu1fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T14:55:07Z"
    mac: ENC[AES256_GCM,data:UY2vLFT8SalrZXXGWz73qfjjxDCAIbLL9QDSzVG1CCsqmhfAao5jXUbEb2qD1fOqvBEeacef1IVDKvevZDW/o8g1K1qWU1O5GGS7LNB8kBKM/Lhfzr/xmGn05vlP3a5Cmkd9734zo7sLINR91ewsl9ePK3G2Y7jWViblyd3SSss=,iv:BnCpOqcctWprK9g60OnFF6Ec3NQ/SHLnI0CWvQg7ptE=,tag:V2P646nDImiNXe18r+eHSQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
