apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  sources:
    - chart: k8s-monitoring
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.0.25
      helm:
        releaseName: grafana-k8s-monitoring
        valueFiles:
          - $manifestRepo/grafana-k8s-monitoring-app/additional-values.yaml
          - secrets://$manifestRepo/grafana-k8s-monitoring-app/secrets.enc.yaml
    - repoURL: https://github.com/Kentaro1043/manifest.git
      targetRevision: main
      ref: manifestRepo
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-k8s-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
