apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.0.25
    helm:
      releaseName: grafana-k8s-monitoring
      valueFiles:
        - additional-values.yaml
        - secrets://secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-k8s-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
