cluster:
  name: oke-cluster

clusterMetrics:
  enabled: true
  node-exporter:
    enabled: true
    metricsTuning:
      useIntegrationAllowList: true

annotationAutodiscovery:
  enabled: true

clusterEvents:
  enabled: true
  #namespaces:
  #  - ai
  #  - misskey

podLogs:
  enabled: true
  #namespaces:
  #  - ai
  #  - misskey

alloy-metrics:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: oke-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    auth:
      type: basic

alloy-singleton:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: oke-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    auth:
      type: basic

alloy-logs:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-logs-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: oke-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    auth:
      type: basic

nodeLogs:
  enabled: true
  journal:
    jobLabel: "integrations/node_exporter"
  labelsToKeep:
    [
      "instance",
      "job",
      "level",
      "name",
      "unit",
      "service_name",
      "source",
      "transport",
      "boot_id",
    ]
  extraLogProcessingStages: |
    stage.labels {
      values = {
        boot_id = "__journal__boot_id",
        transport = "__journal__transport",
      }
    }

integrations:
  cert-manager:
    instances:
      - name: cert-manager
        labelSelectors:
          app: cert-manager
