apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    app: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ai
    spec:
      initContainers:
        - name: init-font-files
          image: busybox:1.37.0@sha256:ce4f0c0a6e67a3a1469e7a8e1fe781f64ba7c652823fdf2d5eac677dd4d095d6
          command: ["/bin/sh", "-c", "
            mkdir -p /font &&
            touch /font/font.ttf &&
            wget -O /font/font.ttf https://github.com/coz-m/MPLUS_FONTS/raw/refs/heads/master/fonts/ttf/Mplus1-Regular.ttf"]
          volumeMounts:
            - name: font-volume
              mountPath: /font
      containers:
        - image: ghcr.io/kentaro1043/ai-arm64:master@sha256:51f3c07b841d7cbc733b80561ac56bd8e102fe2670060d8f1fedd077bea90038
          name: ai
          volumeMounts:
            - mountPath: /ai/config.json
              name: config-json
              readOnly: true
              subPath: config.json
            - mountPath: /ai/font.ttf
              name: font-volume
              readOnly: true
              subPath: font.ttf
            - mountPath: /ai/data
              name: data-volume
      restartPolicy: Always
      volumes:
        - name: config-json
          secret:
            secretName: ai-config-json
        - name: font-volume
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: ai-data-volume
