apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ai
spec:
  selector:
    matchLabels:
      app: ai
  serviceName: ai
  replicas: 1
  template:
    metadata:
      labels:
        app: ai
    spec:
      initContainers:
        - name: init-font-file
          image: docker.io/library/busybox:1.37.0
          command: [
              "/bin/sh",
              "-c",
              "
              mkdir -p /font &&
              touch /font/font.ttf &&
              wget -O /font/font.ttf https://github.com/coz-m/MPLUS_FONTS/raw/refs/heads/master/fonts/ttf/Mplus1-Regular.ttf",
            ]
          volumeMounts:
            - name: font-file
              mountPath: /font

      containers:
        - name: ai
          image: ghcr.io/kentaro1043/ai-arm64:latest
          volumeMounts:
            - mountPath: /ai/data
              name: data
            - mountPath: /ai/config.json
              name: config-json
              readOnly: true
              subPath: config.json
            - mountPath: /ai/font.ttf
              name: font-file
              readOnly: true
              subPath: font.ttf
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 20m
              memory: 128Mi

      volumes:
        - name: config-json
          secret:
            secretName: ai-config-json
        - name: font-file
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
