apiVersion: v1
kind: Secret
metadata:
    name: smtp-credentials
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hfo/MT+bGE12OQgEcf+D9pmArw==,iv:2wTRVg6sgdcdkTPeAFtkJ8Udr3YrUPTeBIWn6q1MQH8=,tag:V4D8ur4jOai42Qv9B13U/Q==,type:str]
    password: ENC[AES256_GCM,data:73muZIwHlSIPnoFm886C3Q==,iv:mUxMi1fdz2NCrukbT6+kDBZFPCKbdgqjGpzeheyjni8=,tag:gA04tgnclVtHEVDVlDXNEQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTHVtaGtvLzNocjV6K2xl
            Q3ZFS3VYeFJHNTl6MnYydTBpWnZHcitoR2xzCnlkTVc2bnl6TldHT3dHV0hIVVpG
            UERUUDZwWmhISWxEV3pDeGFRay9MK1EKLS0tIENxYmtpTnJBdU9RMXpvNFVxVzV4
            WkVuRml0RXZyTGNDOG12RnA5TDlpWDgKFIEZeww7Cb5ePqXXLS4gD8Jc09yQZnKV
            VJK4Q9WwTPynLoFlJfUKVmyZPBDi+6NWeJyPpGyNdYEqiZbwZ9bQfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T17:29:04Z"
    mac: ENC[AES256_GCM,data:sXnECTHpSV4fIdrVdR2rDB8FpSF3xuhwcL7dnPuc5rLudvELGKprxmqBl97fCU2P3+Dm7uVtg/gG4ktlyeVM019oDbS2XC2IAXkREHsHmUE6ePjRGWa1jpoKKGpRGePBN8xR3iJsS9F9vNIbDKi2OFIKeWET92yOEp2XtcKzCJg=,iv:R58gmsdyuVrdC1RoOT+M4BuzX04bEqJMdKv9CTB1xeA=,tag:mmdVfKFh0f1sla4IbwDCAg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
