apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jf.kentaro1043.com`)
      services:
        - name: jellyfin
          port: 8096

  tls:
    secretName: jellyfin-tls
