helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.3.0
    releaseName: jellyfin
    namespace: jellyfin
    additionalValuesFiles:
      - ./additional-values.yaml

resources:
  - ingress-route.yaml
  - certificate.yaml
  - events/github-webhook.yaml
  - events/ingress-route.yaml
  - events/certificate.yaml
  - events/eventbus.yaml

generators:
  - ksops.yaml

configurations:
  - kustomize-config.yaml
