nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: EventSource
        path: spec/github/music-library/apiToken/name
      - kind: EventSource
        path: spec/github/music-library/webhookSecret/name
