nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: EventSource
        path: spec/github/sync-music-library/apiToken/name
      - kind: EventSource
        path: spec/github/sync-music-library/webhookSecret/name
      - kind: WorkflowTemplate
        path: spec/templates[]/steps[]/[]/container/env[]/valueFrom/secretKeyRef/name
