apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-music
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOncePod
