server:
  authModes:
    - server

workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true
    rules:
      - apiGroups: [""]
        resources: ["secrets"]
        resourceNames: ["discord-webhook"]
        verbs: ["get", "list"]

controller:
  workflowDefaults:
    spec:
      onExit: discord-notification
      templates:
        - name: discord-notification
          steps:
            - - name: notify
                templateRef:
                  clusterScope: true
                  name: discord-notification
                  template: send-discord-notification

  workflowNamespaces:
    - "jellyfin"
