server:
  authModes:
    - server

workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true

  controller:
    workflowDefaults:
      spec:
        onExit: discord-notification
        templates:
          - - name: discord-notification
              templateRef:
                clusterScope: true
                name: discord-notification
                template: send-discord-notification

  workflowNamespaces:
    - "jellyfin"
