nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: Middleware
        path: spec/basicAuth/secret
      - kind: ClusterWorkflowTemplate
        path: spec/templates[]/container/env[]/valueFrom/secretKeyRef/name
