apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:yn7EgaO56sLS1KfFCxqAJ49hbbe/nXtwI7v3R+SlUtLUEg2/QcIhQFh1IsCV5PfIB2ehtCv3dYIcOT+u2xjqWxjXNqauM5yVn47ce/I+tb+Zo3gLEF4cSCNI2vE9kaZGiQZs5eEP4hdqSf1zmsIcETJSCRESSbGxc9g+LIxlUZs=,iv:CPHmgUZtngYNEwyVitEgH1LZUuvEAzG5MVxfGnZ36Kc=,tag:SjV7ktsjyW9CrgKPR6McOQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUThGa1BhR29HdzRVanpt
            VEh2RTNRZ0NubjYyOEUwZ0VSbW9Ed1hTZWswCnlabG9qV1FGOTI4SWdJUi9TL2V4
            K0xXTGdCL1VDeGx6SmtEdW56amJGb28KLS0tIHV4dG43OUFtREJxZlNUWkw0M01a
            VUF2TXVFMy8yTzBHZFdSOHhsU0p0YWcKSYRtMEqCevWw/7HZoNivhVUOnJaqE0oD
            ytYQIBBQkdWb9MsK02dh+1CCNk4QlVeAdKTUDyU95LyxPPQX4To0ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T04:54:37Z"
    mac: ENC[AES256_GCM,data:QTqdM2qpAIjBtriVD2BpHhEpjfusQX8FywlfXQmpIlRUcoUuZZFvdjR5h+/VM/jFNBMM9A3GcwWkdHya1awcsSgJD8urGZftaXZ30Ux2dluIE+ChlAP9gy5OErPeOrvLzo00gRb8ohtIgWCZ93L0+1PEEtLyjDMLtb0f+6gBXXg=,iv:L9UvfG8UM4heTT48DLPbTcUA69eagShyvflC9ZVENs0=,tag:A1mAMhXu/0gyArFUFdnGLA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
