apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+3G+NT/MmqpNsQRLNIttyQi+Veo=,iv:HHiWoADgFxx1snkpzbX9Z1WFM3vG2Eyqk9Gkh29kF08=,tag:mzcRldMHDcKvIa0i1GktYQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNUd4S3NQK3BLV3RKZWdL
            czFsYkFibisvYW55bHNTaXhRYXFCVDRxaVNVCnlaSjNsQnVDRlFaS2M0US9QeDJ1
            RkJ6RTAreXhoUVErTFI1NitmRVZTVmsKLS0tIDk3NytZQyttbE9QWElrdmVpemkr
            bmlZNEhaMTBxTnNaS3gveEVyRmNGL2sKdFY3VdxHrgbs4iPGh8ZMqOazAtc5VmsB
            vfXJxfEww49kUGKS5/nmKMoZotOg4iH8RzUkX8sjQX+fojhCWeGU3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T04:42:49Z"
    mac: ENC[AES256_GCM,data:irhqz1j7p90l9CXnp0Q/jwJ8O6rAwPJBpJ8T7fIgdMhDoqNXgJXFPD/LUN3R9e6Ev+a7n3MK0z82OP6sVD46+Pch2bXGtnPCLH1LOawf1nmwWPdDPqDL0VCVTVOKjhrWNfpHOj97BFp7aUiLfM+bwwXLABXIniL5YV2ZKx1LMeA=,iv:aDl9EzgOE55k3YUL9Uunvdu7D6qO18G6fsH5zuFxWTc=,tag:pphhyMsL+9jr7AoIc1KIGw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
