name: invidious

image:
  repository: quay.io/invidious/invidious
  tag: 2.20250517.0-arm64@sha256:9dc74a8911b8ec5eaab978b5b3ab6859336e3d416de220473945ae6573bba7a0
  pullPolicy: IfNotPresent

replicaCount: 3

autoscaling:
  enabled: false

ingress:
  enabled: false

deploymentLabels: {}

affinity: {}

postgresql:
  enabled: false

# https://github.com/iv-org/invidious/blob/master/config/config.example.yml
config:
  db:
    user: invidious
    host: "private.oci.kentaro1043.com"
    port: 65435
    dbname: invidious
  check_tables: true
  external_port: 443
  domain: "inv.kentaro1043.com"
  https_only: true
  hsts: true
  registration_enabled: false
  login_enabled: true
  enable_user_notifications: true
  cache_annotations: true
  default_user_preferences:
    locale: "ja"
    region: "JP"
    captions:
      - "Japanese"
      - "English"
      - "Chinese (Simplified)"

sighelper:
  enabled: true
  image:
    repository: quay.io/invidious/inv-sig-helper
    tag: latest@sha256:39fee87693ef3d71c212d9511f2adb3230783753342321489deab17caa87c42f
    pullPolicy: Always
