apiVersion: v1
kind: Secret
metadata:
    name: misskey-default-config
    namespace: misskey
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    default.yml: ENC[AES256_GCM,data:jWQ6AgnREP3AygnXtDUshJ+X3jYpDhliVT9vvQfkLa6q1M+tq1vCL8Xl7Bo9x6JROprJWmuWfuRdmFG8PkEeB/SVicDZsTY0K0na/VGnT2dRI7EJJSWeiTcPYYjzBXB3NNEB7j4UkhOI717SQ6HGpLAno8qs7T9ApHU2kFSuG2QaCNF2UqFOXKD+lmpEnSFNqau1982HthSbh9NNaLcaBeIiIFO0wR8BIAKqz1Me7jaGeyXFVg7VMUiY3cjUCE6tAiCoSn8HhveI/vdx/EbklQPJ6cJw+lFK0qOgS5YXG0usDhQ9XhUZr94fKRQ/xC3CuMULZJyxIx5cmrnhjpcFUOs6I/6WSuxYXJYQTOBc5EErQ746GHLjrMdtCvMLtOo3xG8SAWKjui4sxziBlp/eXEGkG7eenPHTshqvaTg2vUaKltRp200Jjf5WqNVo1hyx8S+fu4+M9oIGsApAFpaqHy8ahZCquiB3zLa6YoFDNY5lf0wiPz/ooh9nI6dfTw1qTFgNud0ko0wg+RUL98e2Kkg+AFPtsYn98Q3UqX63fGEMUTO/s0o3rr/HgqvLtqxXcf9m4V9YLmPnIKaTQT/DzH1YaMmahO328ImNqoNuCjCPJFt53oMxCmz7EacoyqA8+ti96gHld3rx9kxHdDXG/+gYWPl2Fxjiua5gxkE8i39QVjmCbiwAwyrUiDLM41yql/Zc9p6GcFQ2HwtFETXKjcetEb1HT+jpwz72UWfSwI/uTPM10OjlPDyImedQHxr3PfHhz8zrnwrqMnC3ydtiqLDLlpaf9Vf0oIrbccclDXUDKZkN0EUmGqMmy/EtbE5IZbb0gOf1DtHyAXuNC0kKKf1K7BRYb58KW2iOKHxgIRFHilcDQz70fYYOXgEgTg4/Ugizuw2HeqKSHYloFHvGXBJqpmxFfrol/aj5K3rLvoDYcCTAig57JVLaLLex2Re/+ImvlYd9OoOAtnAVoAChmyVV4N6NBb8qiJ7jwQg4bUanBE9PqdAFlTKcxLU5BklSbP87foBQITYNznlofjMdJLes1I5sNueWlyASg0Aj5mZSnLjKCTQ1pxWUiMfZurGNyUnL+TiD1CvFLpEagmn+uEAFNH0Qpn5YnN3qv1Gy2KmxIECi1YXpvWAoxMQ27qLe/HbzsKhsWae4Pzwati2R17BnRgAz/MmUGURxxGzsR79Kw+YSzdnK/CCDbf1nDBCXGyGsvU286Jw0MdLHhi6kxoluA4lDwNmXwzK4p5vfMczRTqW5POQ5enDIHbQgb1ljj3qdjQy8hNRwqFsE+wn+hgm17A0HTEHoABkh1jiC9SB0rvSd2q80TcsY+a0TzaMm2yUzEoKy2P7VNTxIuHuGxDVrDjDRvInmd18Kmmp6d3tXKjDP5u8fwCfd9ysj2YRP3Z9tO2OWHeYysm28zs2Thq+xcczqnzWUztZX/sJUg1zEj9K9w8zuMcHptvDeACvEPrlCpt3W2FdWTFShK3b+3+4G0qxqR2BLEGSFLcx1MBy2+hsBCwRFlYww+tQ9y17T1i4a0sHrIbq4zVi5MC3/+881IajBJWDKstBfbXvQ8cZwL61qtZ6C7uELAXFhmnlva+NMk0Dj6HKMoGkCbTN043TysN0ZKl7le+2EUyer569OdekiJGRQPMoPNXhKUjQo6QDt4wiT8AmjcUJ16uV0cfph6XB8vVMiFLF6b73NRe34+h0OJG13S5knQInQaAQFhlG6JM+dBmV5IZMx+T5I8brxtkW0pg33fPztAhHpmje/x9+pGaao5TVuty7XybDOQFOdZLn/JCkoVgQXZzo3iHhyiv01ka88jR8=,iv:gOr7QNIhaTDqoz2HAbQtYOZS+IFDjZQROTrs8M/krXw=,tag:gkkAhY2e6ZPuOWe45QPa8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT2taSmUzSGhraXEwaERl
            aFlwVC82QmlkbGlPa3M4dUJXbWZnTlJpeFRBCks5K1Exc1ROUHE2aStOQzZxRFAw
            eWhMN05hSDJWZWt1NVdrUWpzblhlb2cKLS0tIEwrdDgrY01KQ1MrSmZlbU9XWE44
            SCtRL0VIRVBCUzkvaUt0OVZEMzZsbTAK5OdE3pGjymgFSufZqwsGwNzNxmJiyETF
            ByQ/x0f5pf5LUi+xjGVlFNLikwlg5D4X+H9n0scDlo8MY3+GFBEkMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T02:11:41Z"
    mac: ENC[AES256_GCM,data:Cq7A1i788glRiAIKfrdM4yeVWzuIYUuHuchjpqJ3F9XoqG+73ozGD6FfBBjMmilZxKF9k2t64BawkBP+6ir4iYI+g4Uk3jcCl6gz0puN5vyGSFZLW0ITE4ApiBZj1sFkiAx6N1dvOmEsexYsdXtAXs4WpynKavLHuFFEwv3O62A=,iv:HjOeC/ojXPidGhD3mWo2nVPhlbh1xVtbqZSo//zooFs=,tag:1vHujBm27+LeaVlpHAotSQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
