apiVersion: v1
kind: Secret
metadata:
    name: misskey-default-config
    namespace: misskey
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    default.yml: ENC[AES256_GCM,data:cIZM/xGEqKJIxLvlGSpaD5U4n4ZWEAHgvruiAWmVuQhMCYWNBqd6dYJnO1lGNudi3oK8F5tOI53xqesSgMILwUXPP/if2fvQx2xYosKi1VhStcmxTxA0yeQI4ETOONH1JtyYuUjwTDt0saC8pF3B0YT+vtlRosfZdndUZoXVojEZY+ZjHkjoWzwLkaQRWF/kUIar25CTkISACXEndpl6GK1MaMwgVZrg3NVOVl0fNwxXog/JVcCdyonhrbpS2mGIRTZtEkVfEvDMffr44MG7BvUSSQ9lbcUA4bjdRqZbgSfMuEQ8cA8Sm6wjnA+5s6AfK1oVTTabxojQDRSqroUQL4kkmV5b9OPkN3ypvSjglyJYdLYeRUnEzSos1/fIIZlmzEy42b7e4IxbhzU3jfk3rErkLhbaBFQKZo9XoB/3kUC3TrNq7z0Yw4/ggjoSeokRYPHH+24AA/Vn4b4QPyJVCOvBX4ibszhh+m80zpwok/asZkv8nWOI22CPOilCHzZ/vJZTAm2xUBNZeQAd4Eb03spy0ny4WNxTiwfMS5JWPYv2vTybQjnI5+VK9hlcHcqFN+h2y4gmV7VeiqbnFz9KEmt/syGGgqh62VNMGHTYtsXJPxDbgk9L7oso/y4xwvE92brsCbw8wsTEJN0fooHr/ywk8B0pZP1Sj9qu54LfEQ0lKLSrOEUWFKHfxiZiSEVem+2ew1C+Z0TVksLirgd8VYOH8Jiccyg+bgl22cy4xu197cygR0Pr5X7jFyVbN/99f6ORbGwe9aMi8Nm3E/DJrbxe8vND5cjzjGGSIunN9wtC1jKNaw7lO5/9WcZ14nLmgXeMWKj4R+gRs271BsfJJqMWVcEDuGgZFgIaOegbuLj5JQPRWOFNY6vqtBoKEDVaKmugqlkr6sJxd1Z+tuMrpHohXBnD4Emc8JLh64xy5JtuPTAZfb9IVDjWeRhqqkLp/+0ZoAZ2F934kjf0uG4BmPG6RCQsXJdOpm7K0luFje6mU5NWkcHrrPDNB9Cuff/d3dThjlETVKB8jasSis/CERb9mFkmllKNNUa9CesT/YHpdDlPDCfas9dVPBql/RlvxuX5Ywps65PjXGAfUmepUtNgL926BxfwVifJjwWPxom41Si3gzWWg1iTfgr+wyhuPEzTzqdN7P2JthIc/P5NeBAH5jx4x/gXVLEBsyRfkKHZVhnn0qBXg7p50jHet44WZalI5DwQurWH72k/5IbhPfWJAk3tRF48H4KI3ZnURPXtecQ8LPhX4OfpGpZj7yr0LM1TR69jde9JaghX/+e1zmr1bSUYaDO4FGxcElxnppr0gzOcvKyfYH85QXhlbDAXuzxXk475wlhcWRc+whKTLZVMyZIzhhdqRk41a1BEXVzb/SSmTIaAUdXCke9NPqvbInJXvzShhnTr,iv:6hzSF3RS8zftaJwQyiviGqVNdnEzKwSB4BeBLtBAty4=,tag:SOu3H17fNAjaxxLdpav07A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ggmzg2tqehz08qaarxx2utxxa2qvhgd0ds02elcpey6svxwgnshsdhr3kw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa1ZuMzBSdzlNa0RTZXVr
            V1g1bW5Xd0c1UXNoWGY3RGYvNjBybFAxNjFNCmk3THl6eUxnMlB4am11NXJuM2RD
            Yzh4N1pkbU9DRW9uZ2hxNDg0VFhETDQKLS0tIGdIK3M0MklSM1VqWDEvcnF4Uks2
            SnJkMzJHN1FJeWpsUXQrUFhpY0prU3MK2hvb+KsxnDjmgHf3sBldqKrhsIDo6jB3
            zvbZkS2+N4VFekzLnNaLtDHruxNxSPZbxoxycOWHsIv7PBIF77vwrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T05:14:41Z"
    mac: ENC[AES256_GCM,data:L4jzCtynYnGtOxhu7EDbqZHpfr4Oa+NAs8I23WbTGXeUhuRFW+t2Iz7AG7vzBVC094xlnjUr4RWY1ViRdHq7NrLZqUB5o7kULz4XEKXe7tqMI88sYL5+sHs1Z7h4alNcxryBmB2cREJ64xkGAOdjm8T6oK5dfQQNDKd0R+JWMO0=,iv:HXkRlqu9pPkS121PZXemEDe1wGMc/JvPtCcG7gn4skA=,tag:f8V4vzyO2t9C/TN9y6/fwg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
