apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.0.25
    helm:
      releaseName: grafana-cloud
      valueFiles:
        - https://github.com/Kentaro1043/manifest/raw/refs/heads/main/grafana-cloud-app/additional-values.yaml
        - secrets+age-import://sops-age/keys.txt?https://github.com/Kentaro1043/manifest/raw/refs/heads/main/grafana-cloud-app/secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
