apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  secretName: minio-tls
  dnsNames:
    - "api.s3.kentaro1043.com"
    - "s3.kentaro1043.com"
  issuerRef:
    #    name: http-01-issuer-staging
    name: http-01-issuer
    kind: ClusterIssuer
