apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-smtp
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    SMTP_FROM: ENC[AES256_GCM,data:1jkmWCYG4gv63WsyUa4ckhRpOo++raU=,iv:yxiQb6AFhcSbrl+uiyXJwmolNCzmH022q5jn/fy/RRw=,tag:DjiAHDhQulXH4Wptp4P+nQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:s3yB3CCthz05PMo4RX3jTDEKNw==,iv:nh4HpqTdggkOvbAzHBnvgL/O7g6vmT+1UEuOpoSXDc0=,tag:9pkbSX8Bc2sn2AuRaqm9vw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:mmlrEmyqmaps4DDXO7gRAw==,iv:emoPN0PPUsaRlljge+WP1rflZgCCKfxPsu6MRxdapTE=,tag:YACggyntdI2kRLRgmkSZYg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYk42U0ZmRVBKSmVGZVBu
            Y3RveW5UL0FpSmhJQnlVckFPODRoZEZTQm0wCmNvcjFkWnU5Ty9YOUpRcEJaN1RM
            YnhPOEJDSTBlVHhFSFZmRUJPMHpEWjQKLS0tIEhZQ2hFakRZbkVWSjcwYlVGNFhL
            V1FDdi9EYmRXZm95TXBhQ1c0azFCdXMKqmWXDjnKGhjB0iPP6vCew6kUFFmOObF1
            34MLjmnH8od7VBgIK/ClLRDGdVhgdGRYzwVKoNphBvzhLTg7Enuj3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T17:29:22Z"
    mac: ENC[AES256_GCM,data:VQGLgghEP9Pj57DNTO6M8/qRMXc0j4PvBcsSl9I18EyfaebflCuQcZSRg8OTTJV8jLIUZs1koElVZO6TCy4YlsKhIZWgFCZZLVW/qTFBcPM2h/TlXfTA2BkiGnTeyrfzoAztQq0L3qOrFw+41KKi8RZ31S0TGzlV1NlConj+4SU=,iv:Z71y8k8EusscOWsg270msIewhFMz9xjss8b9Ia0LKhs=,tag:e7eZLUDguzoo05QHlsn29Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
