apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secrets/basic-auth.enc.yaml
  - ./secrets/discord-webhook.enc.yaml
  - ./secrets/cgps-api-token.enc.yaml
  - ./secrets/cgps-discord-webhook.enc.yaml
