apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  dnsNames:
    - "nc.kentaro1043.com"
  issuerRef:
    #    name: http-01-issuer-staging
    name: http-01-issuer
    kind: ClusterIssuer
