apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud
spec:
  headers:
    sslRedirect: true
    sslForceHost: true
    forceSTSHeader: true
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true
    contentTypeNosniff: true
    browserXssFilter: true
