crds:
  enabled: true

replicaCount: 2
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: cert-manager
        topologyKey: "kubernetes.io/hostname"

prometheus:
  enabled: true
