apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-01-issuer
spec:
  acme:
    privateKeySecretRef:
      name: dns-01-issuer-secret
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
