apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-issuer

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-issuer-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
